---
title: "Writing a Reproducible Paper in R with WORCS"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'docs/index.html'), output_format = 'html_document'); rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'README.md'), output_format = 'github_document') })
---

This workshop <!--will be taught by [Caspar van Lissa](https://github.com/cjvanlissa), the author of the WORCS package, in collaboration with [RDM Support](https://www.uu.nl/en/research/research-data-management). We--> will give you an overview of the workflow and introduce you to its use, and aim for you to be able to get started on your own reproducible project. [**If you're attending the workshop, make sure to check the Preparation paragraph**](#preparation).

## Why?

Open Science is becoming increasingly popular and relevant, and a world of opportunity is opening up to make your work fully reproducible. This is not without its challenges: best practices for reproducible science include a number of tools that you may never have used or even heard of before. *(Are you using version control? How are you managing your dependencies? Are you writing your manuscript as an executable document?)*


WORCS is an R package that takes you from data to published paper in a single streamlined workflow, making the entire process of your analysis, up to the submission of your manuscript, reproducible. The WORCS workflow optionally facilitates pre-registration, sharing your code and your data (safely!), and the submission of a pre-print.

## Target audience

Anyone who would like to get started with an open and reproducible workflow, without dealing with a mountain of new tools and platforms. The workshop uses R, but prior experience is not required. Having the motivation to step out of your comfort zone — and into a new one — is the most important prerequisite.

<!--## Workshop dates
- tbd-->

## Desired outcome

Attendees will be able to get started on their own open, reproducible project by the end of the workshop.

## Preparation {#preparation}

1. Work through the [Setup vignette: Setting up your computer for WORCS](https://cjvanlissa.github.io/worcs/articles/setup.html) (NOTE: Reserve 1 hour to do this)
1. Download [Allison Horst's Penguin dataset](https://github.com/allisonhorst/palmerpenguins):
    * [CSV file](https://raw.githubusercontent.com/bvreede/worcshop/master/data/penguins.csv)
    * [SPSS file](https://raw.githubusercontent.com/bvreede/worcshop/master/data/penguins.sav)
    * [Excel file](https://raw.githubusercontent.com/bvreede/worcshop/master/data/penguins.xlsx)

## Worcshop slides and documentation

### Workflow demonstration:

[Setting up a `worcs` project in RStudio](https://cjvanlissa.github.io/worcs/articles/workflow.html)

### Presentations (by event):

```{r, echo = FALSE, results= "asis"}
f <- list.files("docs/", pattern = ".html")
f <- f[!f == "index.html"]
tmp <- file.info(file.path("docs", f))
print_f <- paste0(gsub("\\.html$", " (", f), format(tmp$mtime, "%b %y"), ")")
print_f <- print_f[order(tmp$mtime, decreasing = TRUE)]
cat(paste0("* [", print_f, "](",
       paste0("https://cjvanlissa.github.io/worcshop/", f[order(tmp$mtime, decreasing = TRUE)]), ")", collapse = "\n"))
```

<!--[Introducing worcs](https://bvreede.github.io/worcshop/slides/overview_lecture.html)-->

## Further reading
- [Read the preprint](https://psyarxiv.com/k4wde/)
- The [worcs GitHub repo](https://github.com/cjvanlissa/worcs)
- [Markdown cheat sheet](https://www.markdownguide.org/cheat-sheet)

## Links submitted during the workshop
- [TOP guidelines](https://www.cos.io/our-services/top-guidelines)
- [Git User Interfaces](https://git-scm.com/downloads/guis) - recommendation by workshop participant: [GitKraken](https://www.gitkraken.com/)
- [rrtools](https://github.com/benmarwick/rrtools), an attempt to streamline containerization in R
